# Python NDArrays

Python rely on **NumPy** data structures for working with N-dimensional arrays and matrices. NumPy has been developed since the '90s, and it's mainly implemented using **C** programming language structures, resulting in a very fast optimized library even if it runs on python ( if *Vectorized*  operations are used massively).

We import NumPy with the convention of calling the package `np`:

In [1]:
import numpy as np

Let's explore the various ways to create an array in NumPy

In [9]:
np.array([1, 2, 3], dtype=np.int64)

array([1, 2, 3])

Python can also infer the type (NumPy's `dtype`), so we can avoid specifying the type when creating an array.
In the same way as above, let's create a 2 dimensional array

In [10]:
np.array([(1, 2, 3), (4, 5, 6)])

array([[1, 2, 3],
       [4, 5, 6]])

Any "Array Type like" is accepted as a parameter to `array` method

## Creation

Equally spaced arrays can be created thanks to `arange` and `linspace` methods

In [37]:
a = np.linspace(0, 1, 5)
b = np.arange(0, 10, 2)
print(f'a -> {a}')
print(f'b -> {b}')

a -> [0.   0.25 0.5  0.75 1.  ]
b -> [0 2 4 6 8]


Generating an array of Zeros and Ones

In [43]:
zrs = np.zeros(10)
ons = np.ones(10)
print(f'zrs -> {zrs}')
print(f'ons -> {ons}')

zrs -> [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
ons -> [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


We can reshape a vector to N dimensional matrix thanks to the `reshape` method

In [44]:
np.zeros(50).reshape(2, 5, 5)

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

Check if keep the following examples, it's not a strict comparison and it's quite unfair...

We can provide a list comprehension for creating an array as pointed out in Kotlin

In [56]:
np.array([x % 2 for x in range(50)]).reshape(2, 5, 5)

array([[[0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0]],

       [[1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1],
        [0, 1, 0, 1, 0],
        [1, 0, 1, 0, 1]]])

In [57]:
np.fromfunction(lambda i, j: (i + j) % 2, (5, 5))

array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])